In [1]:
import sys
sys.version

'3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]'

In [3]:
pip install numpy

   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/13.0 MB 8.4 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/13.0 MB 8.0 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/13.0 MB 8.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/13.0 MB 7.6 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/13.0 MB 7.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/13.0 MB 7.1 MB/s eta 0:00:01
   ------------------------------ --------- 10.0/13.0 MB 7.0 MB/s eta 0:00:01
   --------------------------------- ------ 11.0/13.0 MB 6.4 MB/s eta 0:00:01
   ------------------------------------- -- 12.3/13.0 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 13.0/13.0 MB 6.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.1'

In [7]:
my_list = [0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [8]:
type(my_list)

list

In [9]:
arr =np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [15]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,8)

array([], dtype=int64)

In [17]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
nd = np.zeros((3,5),dtype=int)
nd

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [26]:
n = np.ones((2,2),dtype=int)

In [27]:
n

array([[1, 1],
       [1, 1]])

In [28]:
nd1 = np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
arr = ([[0,1,2,3,4,5],[10,20,30,40,50],[11,21,31,41,51],[101,201,301,401,501]])
arr[0]

[0, 1, 2, 3, 4, 5]

In [31]:
arr[0][1]

1

In [32]:
arr[3][4]

501

In [37]:
np =[1,2,6,4,5,8,7,2,3,0]
np.sort()
np

[0, 1, 2, 2, 3, 4, 5, 6, 7, 8]

In [40]:
import numpy as np


In [43]:
a = np.array([1,2,3])
b = np.array([6,5,6])

np.concatenate((a, b))

array([1, 2, 3, 6, 5, 6])

In [46]:
x = np.array([[1,2],[3,4]])
y = np.array([[9,8]])

np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [9, 8]])

In [55]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [56]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
np.reshape(a,newshape=(1,6),order='C')
array = ([[0,1,2,3,4,5,6]])

C:\Users\milind rajput\AppData\Local\Temp\ipykernel_27796\1820156616.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a,newshape=(1,6),order='C')


In [59]:
a = np.array([1,2,3,4,5,5])
a.shape

(6,)

In [60]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [61]:
col_vector= a[:,np.newaxis]
col_vector.shape

(6, 1)

In [65]:
data = np.array([0,1,2,3])
data[2]
data[0:2]
data[:1]
data[-1]

np.int64(3)

In [74]:
import numpy as np

In [77]:
a = np.array([[1,2,2],[2,2,2],[1,6,7]])

In [78]:
print(a[a<5])

[1 2 2 2 2 2 1]


In [79]:
five_up = (a>=5)
print(a[five_up])

[6 7]


In [80]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[2 2 2 2 2 6]


In [81]:
c = a[(a>2) & (a<11)]
print(c)

[6 7]


In [82]:
num = (a>5) | (a==5)
print(num)

[[False False False]
 [False False False]
 [False  True  True]]


In [83]:
not_there= np.nonzero(a==42)
print('Not_there')

Not_there


In [86]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
arr = a[3:8]
arr

array([4, 5, 6, 7, 8])

In [89]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])

np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [90]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [91]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [94]:
a = np.array([22,33,44,55])
a.sum()

np.int64(154)

In [95]:
b=np.array([[1,1],[2,2]])
b.sum(axis=0)

array([3, 3])

In [96]:
b.sum(axis=1)

array([2, 4])

In [99]:
data = np.array([1.0,2.3])
d = data*1.6
d

array([1.6 , 3.68])

In [101]:
data.max()

np.float64(2.3)

In [102]:
data.min()

np.float64(1.0)

In [103]:
data.sum()

np.float64(3.3)